select DISTINCT r.CAR_ID from CAR_RENTAL_COMPANY_CAR r join CAR_RENTAL_COMPANY_RENTAL_HISTORY h on r.CAR_ID = h.CAR_ID 

where r.CAR_TYPE = '세단' and h.START_DATE >= '2022-10-01' and h.START_DATE < '2022-11-01'

order by r.CAR_ID desc